---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - harbor.satoruh.org
  resources:
  - harborconnections
  - harborprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.satoruh.org
  resources:
  - harborconnections/finalizers
  - harborprojects/finalizers
  verbs:
  - update
- apiGroups:
  - harbor.satoruh.org
  resources:
  - harborconnections/status
  - harborprojects/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
